# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy Next.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_BASE_PATH: /mrxavi3r.github.io/xavier-portfolio

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install NPM dependencies
      run: npm install
    - name: build static website
    - run: npm run build
    
    - name: Deploy site 🚀
      uses: actions/upload-artifact@v2
      with:
        name: static-site
        branch: gh-pages # The branch the action should deploy to.
        path: /out # The folder the action should deploy.
